[tool.black]
line-length = 88
target-version = ['py311'] # Adjust if using a different Python version primarily

[tool.ruff]
# Enable Pyflakes, pycodestyle error rules & isort
select = ["E", "F", "I"]
ignore = []

# Allow autofix for all enabled rules (when `--fix` is used)
fixable = ["A", "B", "C", "D", "E", "F", "I"]
unfixable = []

exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "venv", # Also ignore venv if not prefixed with .
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
]
line-length = 88

# Allow unused variables in `__init__.py` and `tests/`.
[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
"tests/*" = ["E402"] # Example: Allow module level imports not at top of file in tests

[tool.ruff.isort]
known-first-party = ["dreamerai"] # Treat 'dreamerai' as first-party 